### PR TITLE
Add remove button to unmatched persons

### PR DESCRIPTION
**Pull request by juliaramstedt**
screen shot 2018-02-25 at 12 44 44

### CODE REVIEW

**Comment by juliaramstedt** [comment]
Good question! I definitely need to get more curious about my active record queries... :)

Running rails console, it seems to be doing this query:

```

**Comment by jensljungblad** [comment]
Hm, yeah, it’s probably a Ruby include. Perhaps ‘record.matches.count == 0’ would be pure SQL?

**Comment by juliaramstedt** [comment]
@jensljungblad That would have to be `record.newcomer_matches.count == 0 && record.established_matches == 0`, or

```
if record.newcomer?
   record.newcomer_matches.count == 0
else
  record.established_matches.count == 0
end
```

there is no "matches" relation :(

**Comment by jensljungblad** [comment]
Ahh! Well I guess the second one would be the fastest. Should we go with that for now?

**Pull request merged**
